#!/usr/bin/env bash
#
# adopted from original confluent docker build [1]
# and adjusted to run connect standalone instead.
#
# [1] https://raw.githubusercontent.com/confluentinc/kafka-images/6.1.x/kafka-connect-base/include/etc/confluent/docker/ensure
#

. /etc/confluent/docker/bash-config

echo "===> Check if Kafka is healthy ..."

if [[ -n "${CONNECT_SECURITY_PROTOCOL-}" ]] && [[ $CONNECT_SECURITY_PROTOCOL != "PLAINTEXT" ]]
then

    cub kafka-ready \
        "${CONNECT_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${CONNECT_CUB_KAFKA_TIMEOUT:-40}" \
        -b "$CONNECT_BOOTSTRAP_SERVERS" \
        --config /etc/"${COMPONENT}"/"${COMPONENT}"-worker.properties
else

    cub kafka-ready \
        "${CONNECT_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${CONNECT_CUB_KAFKA_TIMEOUT:-40}" \
        -b "$CONNECT_BOOTSTRAP_SERVERS"
fi