#############################################################
# Integrations                                              #
#############################################################
---
version: '2.4'
services:

  #############################################################
  # Connector HTTP Source                                     #
  #############################################################
  # https://github.com/castorm/kafka-connect-http
  # https://github.com/ueisele/kafka-images/tree/main/connect-standalone
  source-httpcastorm-json-connector:
    image: ueisele/apache-kafka-connect-standalone:${KAFKA_VERSION}
    restart: always
    volumes:
      - source-httpcastorm-json-connector:/var/lib/kafka-connect/
    environment:
      ## Worker Configuration
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 5000
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR,org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,com.github.castorm.kafka.connect.http.client.okhttp.OkHttpClient=DEBUG"
      CONNECT_PLUGIN_INSTALL_EXTENSION_URLS: |
        https://github.com/castorm/kafka-connect-http/releases/download/v0.8.11/castorm-kafka-connect-http-0.8.11.zip
        https://github.com/RedHatInsights/expandjsonsmt/releases/download/0.0.7/kafka-connect-smt-expandjsonsmt-0.0.7.tar.gz
      ## Connector Configuration
      CONNECTOR_NAME: http-source
      CONNECTOR_CONNECTOR_CLASS: com.github.castorm.kafka.connect.http.HttpSourceConnector
      CONNECTOR_TASKS_MAX: 1
      CONNECTOR_HTTP_REQUEST_URL: http://source-httpcastorm-json-httpserver:3000/api/task
      CONNECTOR_HTTP_RESPONSE_LIST_POINTER: /items
      CONNECTOR_HTTP_RESPONSE_RECORD_OFFSET_POINTER: "key=/id,timestamp=/updatedAt"
      CONNECTOR_HTTP_OFFSET_INITIAL: "timestamp=2000-01-01T00:00:00Z"
      CONNECTOR_HTTP_TIMER_INTERVAL_MILLIS: 5000
      CONNECTOR_HTTP_TIMER_CATCHUP_INTERVAL_MILLIS: 5000
      CONNECTOR_KAFKA_TOPIC: source-httpcastorm-json
      CONNECTOR_TRANSFORMS: "valueexpand,valueextract,keyextract"
      CONNECTORPROPERTIES_TRANSFORMS: |
        transforms.valueexpand.type=com.redhat.insights.expandjsonsmt.ExpandJSON$$Value
        transforms.valueexpand.sourceFields=value
        transforms.valueextract.type=org.apache.kafka.connect.transforms.ExtractField$$Value
        transforms.valueextract.field=value
        transforms.keyextract.type=org.apache.kafka.connect.transforms.ExtractField$$Key
        transforms.keyextract.field=key

  #############################################################
  # Logger Source Topic                                       #
  #############################################################
  source-httpcastorm-json-logger:
    image: ueisele/apache-kafka-server-standalone:${KAFKA_VERSION}
    restart: always
    command: |
      kafka-console-consumer.sh \
        --bootstrap-server kafka:9092 \
        --topic source-httpcastorm-json \
        --group source-httpcastorm-json-logger \
        --from-beginning \
        --property print.key=true \
        --property print.timestamp=true

  #############################################################
  # Source HTTP Server                                        #
  #############################################################
  source-httpcastorm-json-httpserver:
    image: integration-app-httpserver:latest
    build:
      context: ../../apps/httpserver/
    restart: always
    ports:
      - 23000:3000

volumes:
  source-httpcastorm-json-connector:

networks:
  default:
    name: ${DOMAIN_NAME}
    external: {}